name: Publish
on:
  release:
    types: [published]
jobs:

  publish-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU # Needed for multi-platform builds (e.g., arm64 on amd64 runner)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx # Needed for multi-platform builds
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        id: docker_login
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
           ghcr.io/${{ github.repository }}
          tags: |
            type=raw,priority=100,value=${{ github.sha }}
            type=raw,priority=150,value=${{ github.run_id }}-${{ github.run_attempt }}
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest
            ghcr.io/user/app:latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}         
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile # Adjust path if your Dockerfile is elsewhere
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.docker_login.outputs.registry }}/${{ github.event.repository.name }}:latest
          cache-to: type=inline,mode=max
  
